name: KRC Complain

on:
  workflow_dispatch: # enable manual run
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  schedule:
    - cron: '0 7 * * *' #  Runs at 07:00 UTC which means UTC+3 is Turkish time :) where the firm operates


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Complain on KRC
      run: |
        python main.py
      env:
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        COMPLAIN_MESSAGE: ${{ secrets.COMPLAIN_MESSAGE }}
        EMAIL: ${{ secrets.EMAIL }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Move SS to screenshots
      run: |
        mv contact-page-*.png screenshots/

    - name: Commit SS push
      run: |
        git config --global user.email "robotcuk@randommail.com"
        git config --global user.name "robotcuk"
        git add 'screenshots/contact-page-*.png'
        git commit -m "${{ steps.date.outputs.date }} Complain is done to KRC on ${{ steps.date.outputs.date }}"
        git push origin -f main
      env:
        GITHUB_TOKEN: ${{ secrets.ROBOTCUK }}

    - name: Upload screenshot to artifact
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: |
          ./screenshots/contact-page-*.png
